# Generated by Django 4.2.4 on 2024-02-08 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qname', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('Level', models.CharField(max_length=200)),
                ('problemLink', models.URLField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('mentorId', models.IntegerField()),
                ('allotedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('SubmittedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('submitedMentees', models.ManyToManyField(blank=True, to='clients.mentee')),
            ],
        ),
    ]
