# Generated by Django 4.2.4 on 2026-01-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_alter_mentor_supermentor"),
        ("Questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.mentee"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Questions.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "mentee")},
            },
        ),
    ]
