# Generated by Django 4.2.4 on 2026-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Questions", "0002_questionassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="scope",
            field=models.CharField(
                choices=[("TEAM", "Team"), ("ALL", "All")],
                default="TEAM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="Level",
            field=models.CharField(
                choices=[("1", "Easy"), ("2", "Medium"), ("3", "Hard")], max_length=200
            ),
        ),
    ]
