# Generated by Django 4.1.7 on 2023-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('openInnovation', models.BooleanField()),
                ('member1', models.CharField(max_length=100, null=True)),
                ('member2', models.CharField(max_length=100, null=True)),
                ('member3', models.CharField(max_length=100, null=True)),
                ('member4', models.CharField(max_length=100, null=True)),
                ('member5', models.CharField(max_length=100, null=True)),
                ('member6', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
