# Generated by Django 4.1.7 on 2023-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortlistedTeams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedteam',
            name='openInnovation',
            field=models.BooleanField(default=False),
        ),
    ]
