# Generated by Django 4.2.4 on 2024-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[['CSE', 'CSE'], ['IT', 'IT'], ['ECE', 'ECE'], ['ELEC', 'ELEC'], ['MECH', 'MECH'], ['CHEM', 'CHEM'], ['CIVIL', 'CIVIL'], ['META', 'META'], ['MIN', 'MIN'], ['BIOMED', 'BIOMED'], ['BIOTECH', 'BIOTECH'], ['MCA', 'MCA']], default='CSE', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/uploads/team')),
                ('member_type', models.CharField(choices=[('MNG', 'Manager'), ('HCO', 'Head Co-ordinator'), ('OCO', 'Overall Co-ordinator'), ('EXC', 'Executive')], default='EXEC', max_length=100)),
                ('year', models.IntegerField(default=2024)),
                ('domain', models.CharField(choices=[['Technical', 'Technical'], ['sponsorship', 'sponsorship'], ['PR & Marketing', 'PR & Marketing'], ['Documentation', 'Documentation'], ['Design', 'Design'], ['Video Editing', 'Video Editing']], default='PR & Marketing', max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TeamData',
        ),
    ]
