# Generated by Django 4.2.4 on 2025-10-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='drive_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
