# Generated by Django 4.2.4 on 2024-09-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_member_delete_teamdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='TeamMembers',
        ),
    ]
