# Generated by Django 4.2.4 on 2023-09-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_alter_teamdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='data',
            field=models.CharField(max_length=1000000),
        ),
    ]
