# Generated by Django 4.2.4 on 2023-09-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_alter_teamdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='data',
            field=models.JSONField(),
        ),
    ]
