# Generated by Django 4.2.4 on 2024-01-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
