# Generated by Django 4.2.9 on 2025-01-02 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_mentor_mentorteam_alter_mentee_codechefid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='image',
            field=models.URLField(blank=True, default='https://avatars.githubusercontent.com/u/5783068?v=4', null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.URLField(blank=True, default='https://avatars.githubusercontent.com/u/5783068?v=4', null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
