# Generated by Django 4.2.4 on 2025-01-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_mentee_image_alter_mentee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_rank',
            field=models.IntegerField(default=0),
        ),
    ]
