# Generated by Django 4.2.9 on 2025-01-19 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_mentee_mentee_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='image',
            field=models.URLField(blank=True, default='https://avatar.iran.liara.run/public/48', null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.URLField(blank=True, default='https://avatar.iran.liara.run/public/8', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
