# Generated by Django 4.2.4 on 2026-01-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_mentee_image_alter_mentor_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="supermentor",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
