# Generated by Django 4.2.4 on 2026-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_mentor_supermentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="supermentor",
            field=models.BooleanField(default=False),
        ),
    ]
