# Generated by Django 4.1.7 on 2023-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/uploads/events/')),
            ],
        ),
    ]
