# Generated by Django 4.1.7 on 2023-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Glimpses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glimpse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/uploads/glimpses/')),
            ],
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
